apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web-tier
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: frontend
      tier: web-tier
      project: expense
  template: 
    metadata: 
      labels: 
        app: frontend
        tier: web-tier
        project: expense
    spec: 
      containers:
      - name: frontend
        image: vamsidocker012/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
  name:  frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector: 
    app: frontend
    tier: web-tier
    project: expense
  ports: 
    - name: frontend-port
      protocol: TCP
      port: 80
      targetPort: 80

      